newImage("Untitled", "8-bit black", 512, 512, 1);
makeOval(157, 160, 18, 22);
setForegroundColor(255, 255, 255);
run("Fill", "slice");
run("Duplicate...", " ");
run("Translate...", "x=4 y=4 interpolation=None");
selectWindow("Untitled");
saveAs("Tiff", "/Users/tischi/Desktop/synthetic_image_01_ch1.tif");
selectWindow("Untitled-1");
saveAs("Tiff", "/Users/tischi/Desktop/synthetic_image_01_ch1.tif");
